import React, { Component } from 'react';
import { View, Text, TouchableOpacity, Image, ScrollView } from 'react-native';
import { images,colors } from '../globalstyles/Style';
import styles from './Style';

export default class Policy extends Component {
    render() {
        return (
            <View style={{flex:1,backgroundColor:'#fff'}}>
                <ScrollView>
                    <TouchableOpacity onPress={() => this.props.navigation.goBack()}>
                        <Image source={images.back} style={styles.backimg} tintColor='#000' />
                    </TouchableOpacity>
                    <View style={styles.content}>
                        <Text style={[styles.heading,{color: colors.primary}]}>Privacy Policy</Text>

                        <Text style={styles.footertxt}>
                        1. Introduction
We, at ArcadeSky Technologies Pvt Ltd. (hereinafter collectively referred to as “ATPL”), are committed to respecting your online privacy and recognize the need for appropriate protection and management of any personally identifiable information you share with us. This Privacy Policy ("Policy") describes how ATPL collects, uses, discloses and transfers personal information of users through its websites and applications, including through www.RajputLagn.com & , mobile applications and online services (collectively, the "Platform").

This policy applies to those who visit the Platform, or whose information ATPL otherwise receives in connection with its services (such as contact information of individuals associated with ATPL including partners) (hereinafter collectively referred to as “Users”). For the purposes of the Privacy Policy, “You" or “Your” shall mean the person who is accessing the Platform.

2.Types of Personal Information collected by ATPL
“Personal information” (PI) - means any information relating to an identified or identifiable natural person including common identifiers such as a name, an identification number, location data, an online identifier or one or more factors specific to the physical, physiological, genetic, mental, economic, cultural or social identity of that natural person and any other information that is so categorized by applicable laws.

We collect information about you and/or your usage to provide better services and offerings.

The Personal Information that we collect, and how we collect it, depends upon how you interact with us. We collect the following categories of Personal Information in the following ways:

We may collect your Personal Information such as name, email address, date of birth, mobile number, mother tongue, password, country, state/nationality, gender, current location, city, pin code, marital status, height, occupation, income etc.
When you complete your profile, you can share with us additional information, such as details on your personality, family details, contact address and other details about you, as well as content such as photos. To add certain content, like pictures or videos, you may allow us to access your camera or photo album. Some of the information you choose to provide us may be considered “special” or “sensitive” in certain jurisdictions, for example your ethnic origins, religious beliefs, sub caste, physical and mental conditions. By choosing to provide this information, you consent to our processing of the information., when the you sign up as a member or you set up an alert on the Platform, we may reach out to you as per your settings;
Information that one would usually include in a matrimonial profile, including name, contact details such as e-mail address and mobile number, date of birth, educational qualifications, data relating to your current employment, income photographs, visa and work status etc. when you register on the Platform;
Information about the services that you use and how you use them, including log information and location information, when you are a user of the services through the Platform;
We may collect your Personal Information such as name, age, contact details, preferences, etc. through surveys and forms, when you choose to participate in these surveys etc.;
We may collect your documents on age, address, income etc. for verification purposes to provide additional credibility to your profile.
When you communicate with ATPL or use the Platform to communicate with other members (including advertisers, Users (such as partners), we collect information about your communication and any information you choose to provide;
When you visit the Platform, we use cookies to automatically collect, store and use technical information about your system and interaction with our Platform;
When you use a device to access the Platform, ATPL may collect technical or other related information from the device as well as the device location;
To the extent permitted by law, ATPL may record and monitor your communications with us to ensure compliance with our legal and regulatory obligations and our internal policies. This may include the recording of telephone conversations.
We may collect your and your partner’s information such as but not limited to name, gender, date and time of birth, city, state, country and email if you avail our horoscope services.
We may collect, process and store your user ID associated with any social media account (such as your Facebook and Google account) that you use to connect with us or to avail our services
When you use your social media account information to access the Platform, or otherwise connect your social media account with the services of the Platform, you consent to our collection, storage, and use, in accordance with this Privacy Policy, of the information that you make available to us through the social media interface. Please see your social media provider's privacy policy and help centre for more information about how they share information when you choose to connect your account.
3. How ATPL may use your Personal Information
We will only use your personal data in a fair and reasonable manner, and where we have a lawful reason to do so.
Our use of your personal data depends on the purpose for which you interact with us. We may process your Personal Information for the following purposes:

Protecting our Users and providing you with customer support;
Our automated systems analyse your content to provide you with customized search results and recommendations.
Send alerts and emails such as match alert mails, membership mails, kundli alert mails, visitor alert mails, new matches mails, contact alert mails, photo request mails, service mails, promotional mails, SMS alerts and call alerts(s) to you ( To unsubscribe, please visit the Alert Manager link on your profile).
We also process your chats with other users of the Platform, for purposes such as fulfilment of legal obligations, monitoring for offensive or menacing content etc.
We use information collected from cookies and other technologies, like pixel tags, to improve your user experience and the overall quality of our services (for more information please refer to paragraph 4 below). When showing you tailored ads, we will not associate an identifier from cookies or similar technologies with sensitive categories, such as those based on race, religion, sexual orientation or health, improving the Platform and its content to provide better features and services.
Conducting market research and surveys with the aim of improving our products and services.
Sending you information about our products and services for marketing purposes and promotions;
Preventing, detecting, investigating and taking action against crimes (including but not limited to fraud and other financial crimes), any other illegal activities, suspected fraud, or violations of the Platform’s Terms of Use in any jurisdiction
To the extent required for identity verification and due diligence checks if so undertaken.
Establishing, exercising or defending legal rights in connection with legal proceedings (including any prospective legal proceedings) and seeking professional or legal advice in relation to such legal proceedings.
4. Cookies and Other Tracking Technologies
Some of our web pages utilize "cookies" and other tracking technologies. A "cookie" is a small text file that may be used, for example, to collect information about web-site activity. Some cookies and other technologies may serve to recall Personal Information previously indicated by a user. Most browsers allow you to control cookies, including whether or not to accept them and how to remove them.

You may set most browsers to notify you if you receive a cookie, or you may choose to block cookies with your browser, but please note that if you choose to erase or block your cookies, you will need to re-enter your original user ID and password to gain access to certain parts of the Platform.

Tracking technologies may record information such as Internet domain and host names; Internet protocol (IP) addresses; browser software and operating system types; clickstream patterns; and dates and times that our site is accessed. Our use of cookies and other tracking technologies allows us to improve our Platform and the overall website experience. We may also analyse information that does not contain Personal Information for trends and statistics.

 
5. The Basis/ Grounds which we rely on for collection and processing of your Personal Information:
Your Personal Information is collected and processed by ATPL based on the following legal grounds depending upon the nature of Personal Information and the purposes for which it is processed.

Consent:
ATPL relies on your consent in order to process your Personal Information in certain situations. If ATPL requires your consent to collect and process certain Personal Information, as per the requirements under the applicable data protection laws, your consent is sought at the time of collection of your Personal Information and such processing will only be performed where consent is secured.

Compliance with a legal obligation:Your Personal Information may be processed by ATPL, to the extent that such processing is necessary to allow ATPL to comply with a legal obligation. An example of this would be if ATPL is required to disclose your Personal Information to respond to a court order or if ATPL is required to retain specific records for a fixed period to comply with requirements under any applicable law.


6. Information Sharing and Disclosure
Third Party Services: Third parties provide certain services available on the Platform on its behalf. Platform may provide information, including Personal Information and special/ sensitive personal information, that the Platform collects from its users to third-party service providers to help us deliver programs, products, information, and services. Service providers are also an important means by which the Platform maintains its services and mailing lists.

We restrict access to your Personal Information to employees who we believe reasonably need to know/or that information to fulfil their functions to provide, operate, develop, or improve our products or services.

ATPL does not disclose, transfer or share your Personal Information with others except with:
Our affiliates and group companies to the extent required for our internal business and/or administrative purposes and/or general corporate operations and for provision of services;
Third parties including enforcement, regulatory and judicial authorities, if we determine that disclosure of your Personal Information is required to a) respond to subpoenas, court orders, or legal process, or to establish or exercise our legal rights or defend against legal claims; or b) investigate, prevent, or take action regarding illegal activities, suspected fraud, situations involving potential threats to the physical safety of any person, violations of Platform’s Terms & Conditions or as otherwise required by law;
In the event of a merger, acquisition, financing, or sale of assets or any other situation involving the transfer of some or all of ATPL’s business assets we may disclose Personal Information to those involved in the negotiation or transfer.
Third party service providers and marketing partners that ATPL engages to a) provide services over the Platform on ATPL’s behalf; b) maintain the Platform and mailing lists; or c) communicate with you on ATPL’s behalf about offers relating to its products and/or services. ATPL will take reasonable steps to ensure that these third-party service providers are obligated to protect your Personal Information and are also subject to appropriate confidentiality / non-disclosure obligations.
Third party advertisers to display advertisements to you when you visit the Platform. The third-party advertisers include financial service providers (such as banks, insurance agents, stock brokers and mortgage lenders) and non-financial companies (such as stores, airlines, and software companies). These companies may use information about you and your visits to this Platform and other web sites to provide advertisements on this Platform.

The Company does not provide any Personal Information to the advertiser when you interact with or view a targeted advertisement. However, if you interact with or view an advertisement, the advertiser may make certain assumptions and, in the process, learn certain Personal Information about you. For instance, if you view and click an advertisement that is targeted towards women in the age group 18- 24 from a specific geographic area, the advertiser may assume that you meet the relevant criteria.

ATPL does not intend to transfer Personal Information without your consent to third parties who are not bound to act on ATPL's behalf unless such transfer is legally required.

If your Personal Information is transferred outside India, we take the necessary steps to protect your Personal Information in accordance with applicable data protection laws.

7. Third Party Content:
Please be aware that the Platform sometimes contains links to other sites that are not governed by this Privacy Policy. Users may be directed to third-party sites for more information, such as advertisers, blogs, content sponsorships, vendor services, social networks, etc.

ATPL makes no representations or warranties regarding how your information is stored or used on third-party servers. We recommend that you review the applicable privacy statements and policies of each third-party site linked from the Platform to determine their use of your personal information.

8. Children
To use the Platform, you agree that you must be the minimum age (described in this paragraph below) or older.

The minimum age for these purposes shall be eighteen (18), however if local laws require that you must be older for ATPL to be able to lawfully provide the services over the Platform to you then that older age shall apply as the applicable minimum age.

If you are under the age of 18 or the age of majority in your jurisdiction, you must use the Platform under the supervision of your parent, legal guardian or responsible adult.

9. Retention of Personal Information
Your Personal Information will not be retained by ATPL any longer than it is necessary for the purposes for which the Personal Information is processed and/or in accordance with legal, regulatory, contractual or statutory obligations as applicable.

At the expiry of such periods, your Personal Information will be deleted or archived in compliance with applicable laws

10. Controlling your personal information
You have the right to invoke your rights which are available to data principals or data subjects (as per applicable laws and regulations) in relation to your Personal Information which is being processed by ATPL.

ATPL provides you the ability to keep your Personal Information accurate and up-to-date. If at any time you would like to a) rectify, update or correct your Personal Information; b) obtain confirmation on whether or not your Personal Information is processed by it; c) access your Personal Information or exercise your right to data portability; or d) exercise your right to restrict the continuing disclosure of your Personal Information to any third party by ATPL in certain circumstances, you are requested to contact us using the contact details mentioned below. We will require you to provide a valid proof of your identity, in order to ensure that your rights are respected.

For the exercise of certain rights, you may be required to approach the relevant authority / designated officer as per the provisions of the applicable data protection laws.

ATPL may in accordance with the provisions of applicable data protection laws, charge a fee for fulfilling your request, in particular in case of excessive or manifestly unfounded request. Further you acknowledge that the above mentioned rights are not absolute and are subject to limitations as per the applicable data protection laws.

11. Confidentiality and Security
The security and confidentiality of your Personal Information is important to us and ATPL has invested significant resources to protect the safekeeping and confidentiality of your personal data. When using external service providers acting as processors, we require that they adhere to the same standards as ATPL does. Regardless of where your Personal Information is transferred or stored, we take all steps reasonably necessary to ensure that personal data is kept secure.
We seek to ensure compliance with the requirements of the Information Technology Act, 2000 and Rules made there under to ensure the protection and preservation of your privacy. We have physical, electronic, and procedural safeguards that comply with the laws prevalent in India to protect your Personal Information. By accepting the terms of this Privacy Policy, you agree that the standards and practices being implemented by us, are reasonable and sufficient for the protection of your Personal Information.
12. Social media
ATPL operates channels, pages and accounts on some social media sites to inform, assist and engage with customers. ATPL monitors and records comments and posts made on these channels about itself in order to improve its products and services.

Please note that you must not communicate the following information to ATPL through such social media sites:

sensitive personal data including (i) special categories of personal data meaning any information revealing racial or ethnic origin, political opinions, religious or philosophical beliefs, or trade union membership, and the processing of genetic data, biometric data for the purpose of uniquely identifying a natural person, data concerning health or data concerning a natural person's sex life or sexual orientation and (ii) other sensitive personal data such as criminal convictions and offences and national identification number ;

Excessive, inappropriate, offensive or defamatory content. ATPL is not responsible for any information posted on those sites other than the information posted by its employees on its behalf. ATPL is only responsible for its own use of the Personal Information received through such sites.
13. Changes to this Privacy Policy
ATPL reserves the right to update, change or modify this Privacy Policy at any time. The Privacy Policy shall come to effect from the date of publication of such update, change or modification
14. Disclaimer
ATPL does not store any account related information or any credit / debit card details. ATPL shall not be liable for any loss or damage sustained by Users as a result of any disclosure (inadvertent or otherwise) of any information concerning the User's account, credit cards or debit cards in the course of any online transactions or payments made for any products and/or services offered through the Platform.

In case any Personal Information is shared by you with ATPL, which is not requested by ATPL during registration, (whether mandatory or optional), ATPL will not be liable for any information security breach or disclosure in relation to such information.

If you have any questions regarding this Privacy Policy or the protection of your Personal Information, please contact ATPL’s Data Protection Officer/ Grievance Officer at the following:
15. Data Protection Officer/ Grievance Officer
In case you have any complaints and/or grievances in relation to the processing of your Personal Information you can send your complaints via email to our grievance officer:

ArcadeSky Technologies Pvt Ltd.
Hello@rajputlagn.com
 
 


                        </Text>

                        <Text style={[styles.heading,{color: colors.primary}]}>Terms of use</Text>

                        <Text style={styles.footertxt}>
                        Term of Use 
PLEASE READ THESE TERMS AND CONDITIONS CAREFULLY .
 
The Licensed Mobile Application  -Rajput Lagn for Accessing the Site (including all associated media and online or electronic documentation) (“the Application”), are owned and operated by Arcadesky technology pvt  (India) Limited (“Company”). The mobile  Application is  hereinafter collectively referred to as “Platform”.
 
The Company makes available its services and products to you, through the Platform on the condition that you abide by these Terms and Conditions, as updated from time to time. If you do not accept the Terms and Conditions or you do not meet or comply with their provisions, you should not use or access the Platform and/or avail of the Company’s services or products via the Platform.
The Platform is an intermediary as defined under sub-clause (w) of Section 2 of the Information Technology Act, 2000. Visitors to the Platform are granted a nonexclusive, limited license to use and access the content and services offered in accordance with these Terms and Conditions (the "License").
A Visitor to the platform, whether or not he/she has made any payment for availing access and/or services on the Platform, including the general browsers of the Platform, whether registered or not, are hereinafter referred to as “User/Users”.
BY THE POSITIVE ACTS OF A USER ACCESSING THE PLATFORM, THE USER AGREES TO BE BOUND BY THE TERMS AND CONDITIONS SET FORTH BELOW (“Terms”). IF A USER DOES NOT AGREE WITH ANY OF THESE TERMS AND CONDITIONS, HE/SHE SHOULD NOT ACCESS OR USE THE PLATFORM.
1. The Platform is owned and operated by Rajput Lagn Internet Services, a division of Arkadesky technology (India) Ltd. (hereinafter referred to as ”Company”), which term shall, for the purposes hereof, be deemed to include its subsidiaries, affiliates, partners, shareholders, directors, executives, officers, employees, agents, attorneys, accountants and any person vested with any responsibility for any task relating to the affairs of the company), with its registered office 
2. The Platform is intended only to serve as a preliminary medium of contact and information for Users who have a bona fide intention to enter into a matrimonial alliance (“Purpose”). The Platform does not purport to be a marriage or business bureau or a dating /contact website.
3. Company presumes that every User who logs on to the Platform has a bona fide intention to get married / enter into a matrimonial alliance and not otherwise. Company under no circumstances shall be responsible for any loss or damage resulting from anyone's use of the Platform or the services offered on the Platform and / or any content posted on the Platform or transmitted to Users. The exchange of matrimonial profile(s) through or by the Platform should not in any way be construed as a matrimonial offer and/or recommendation from or by the Company. Company shall not be responsible for any loss or damage to any individual arising in/out of, or subsequent to, matrimonial relations established pursuant to use of the service provided by Company.
4. In order to share the profiles , you may use whatsapp share  gmail  and other sharing apps .  If you do so, you authorize us to access and use these account information that you choose to display publicly. For more information regarding the information we collect from Users and how we use it, Users are advised to visit our Privacy Policy.
Company collects information / data including, without limitation, e-mail id, address, first name, last name, telephone/mobile number, date of birth, age, gender, ethnic/cultural background, appearance, religion, occupation, preferences, life style information, general geographical location (“User Data”) from Users in order to enable them to create their profiles on the Platform. Apart from this, certain other health related information, including physical and mental disabilities are also collected. The User Data so collected is entered in a program especially devised for matching profiles and to provide matches for Users based on their pre-selected partner preferences criteria. User Data is displayed only after taking prior consent of Users. Company does not collect financial information of Users such as credit card/debit card numbers/bank accounts numbers etc. Company shall not be able to provide access to the Platform and/or create profiles of Users if the requisite User Data is not provided by the Users. User hereby consents to usage of his/her User Data to be displayed to other Users on the Platform.
Users hereby give us permission to use the information about their activities and actions that they have taken on the Platform in connection with ads, offers and other sponsored content that the Company displays on the Platform, without charging any fees to the Users. The Company uses data and information about Users to make relevant suggestions and recommendations to its Users.
5. The User Data is uploaded by the Users themselves or through any of the Rajput Lagn offline help centers displayed on the Platform. Company may, at its sole discretion, include all or any portion of the listing intimidated by a User for display on the Platform in any other media including the matrimonial sections of other platforms including but not limited to print media, community associations, websites, television shows, DTH/IPTV Services, mobile wap sites etc. at no extra costs to the Users and Company shall not be held liable for usage/publicity of such information / data.
6. Users undertake not to duplicate, download, publish, modify and distribute material on the Platform unless specifically authorized by the Company in writing. Users undertake not to establish any deep link or other connection to any specific page of the Platform without obtaining prior written consent of the Company.
7. Users undertake to use the Platform for their personal purposes. Using content from the Platform for creating derivative works with a commercial motive without prior written consent from the Company is strictly prohibited.
8.The Company takes measures including technological means on the Platform to exclude robots, scripts, programs etc. from crawling or scraping content on the Platform. Users undertake not to circumvent these methods.
9. Any advice, counseling, recommendations or information provided on the Platform including information of Users may not be necessarily correct, true or reliable, and that any reliance placed thereon and any action taken on the basis thereof shall be entirely / solely at the risk of the concerned User. Users hereby agree that access to the content available on the Platform is provided by Company to Users on an ‘AS-IS’ and ‘AS-AVAILABLE’ basis. Users wishing to use the information so provided are advised to conduct their own due diligence, in respect of the content on the Platform, at their own initiative, cost and effort. Company does not advise / recommend a User to establish any contact / interaction with other Users or any based on the data / information as furnished in such User’s profile / photograph etc. and the User opting to build contact or interact shall do it solely at his / her own risk. Company cannot be held responsible or liable, in any manner whatsoever, in respect of any reliance placed on any information displayed / placed on the Platform, since the same purports merely to act as indicators of the general scenario in the related behalf.
10. Company does not authenticate, vet, screen, endorse or investigate any information or assertion composed in the matrimonial listings, or any other content on the Platform, nor does it in any manner whatsoever certify or attest the same to be correct or true. It does not endorse matches and profiles in any manner, but an implied presumption is cast on the Users that the information(s) furnished are exclusively / solely to carve out / frame a suitable profile for the purpose of matrimonial alliance based on the partner preferences criteria set by the Users. All due diligence, effort and initiatives must be exercised by those wishing to use any information found on the Platform, and should take adequate precautions with the full and complete knowledge that all information contained in the matrimonial listings have been placed there directly by Users of the Platform without any prior intimation, consent or verification of or by Company.
Users of the Platform are prohibited from uploading, posting, transmitting, updating or sharing any information that:
a) belongs to another person and to which the user does not have any right to;
b) is grossly harmful, harassing, blasphemous, defamatory, obscene, pornographic, paedophilic, libellous, invasive of another's privacy, hateful, or racially, ethnically objectionable, disparaging, relating or encouraging money laundering or gambling, or otherwise unlawful in any manner whatever; harm minors in any way;
c) infringes any patent, trademark, copyright or other proprietary rights;
d) violates any law for the time being in force;
e) deceives or misleads the addressee about the origin of such messages or communicates any information which is grossly offensive or menacing in nature; impersonate another person;
f) contains software viruses or any other computer code, files or programs designed to interrupt, destroy or limit the functionality of the Platform ; threatens the unity, integrity, defence, security or sovereignty of India, friendly relations with foreign states, or public order or causes incitement to the commission of any cognisable offence or prevents investigation of any offence or is insulting any other nation.
Company may, without notice in its sole discretion, and at any time, terminate or restrict a User’s usage or access to the Platform (or any part thereof) and/or take down any content uploaded by a User for any reason, including, without limitation, that Company based on its judgement and perception believes the a User has violated or acted inconsistently with the letter or spirit of these Terms.
11. Company is an online service provider for Users to create their own/unique profiles envisaging certain personal (optional) information(s) and User Data are to be displayed on the Platform, which information is used by Users for the Purpose. Company does not share User Data with other Users or third parties with the prior consent of the User. Although Company shall take all reasonable precautions, Company shall not be responsible in case such User Data so displayed on the Platform being unauthorisedly copied / printed / published / forged / superimposed / manipulated etc. or misused by any User. Users shall indemnify Company from all kind of losses / damages which Company may suffer from any activities carried out by them through improper use of the Platform/service provided by Company.
12. By listing a matrimonial profile, or a business or personal listing or a link, or any content or listing, on the Platform, the concerned User making or posting such listing, and the person or persons responsible for such posting or listing, shall be deemed to have agreed to hold Company harmless and protected against any suit or complaint, civil, pecuniary or criminal, and against any claims or damages (including, without limitation, interests, fines and penalties) which may be brought against or levied on Company on account of any matter arising out of, or relating to, such posting / listing or response received from such posting/listing.
13. Whilst using the Platform an obligation is cast upon Users to only provide true and correct information and in the case of creating a profile Users undertake at all times to keep the information up to date. Company does not represent or endorse the accuracy or reliability of any member / visitor profile, advice, opinion, statement or other information displayed / uploaded through the service by the Company. Company or any of its owners, staff or agents are not responsible under any circumstances for any action/display whether direct or indirect, which occurs as a result of online display of information in the nature of illicit material / material that may be offensive to visitors / members or is patently offensive to the on-line community or any material which may promote racism, bigotry, hatred or physical/mental harm of any kind to any group or individual or transmit any chain letters or junk mail or unsolicited mass mailing or spamming or obscene material to other users / members. Company does not monitor the conduct of Users and therefore Company does not take the responsibility of any conduct by Users who may avail / obtain / use / exploit the online service provided by Company in order to harass, abuse or harm another Users or use the said online service to promote / advertise / solicit anything without their prior consent or an act in any manner which may threaten the safety of other Users.
14. Company reserves the right to remove / delete any content / message / photo(s) / profile or cancel the registration / membership of a User either upon a complaint received from another User or upon discovery of the same on its own or based on its sole judgment and perception and it shall without notice stop providing the service entitled to a User and forfeit all other incidental service(s) with immediate effect along with the fee/tenure of registration as well as take appropriate legal action against such User. By listing a profile on the Platform, it is deemed that the said User has an intention to get married and in case it appears to Company that at the time of listing the profile or subsequently such User had no intention to enter into a matrimonial alliance or has changed his/her intention, then Company shall reserve the right to remove / delete such profile from the Platform and initiate prosecution under the law or take such steps as may be advised from time to time. By using the Platform, it is deemed that the User agrees not to post any content or views that may be considered threatening, abusive, vulgar, obscene or otherwise objectionable or act illegally or otherwise harass another user; put wrong or misleading information in any of the details of his/her own profile; impersonate another or use the site for any commercial purposes; or interfere with or disrupt the operation of this site, or disobey any reasonable requirements, procedures or policies imposed by Company from time to time.
15. Nothing comprised in the contents of the Platform is intended or meant to induce or persuade or convince or invite any person whatsoever to perform any action or do any such thing, or not to perform or do, where such performance or doing, or non-performance or not doing, constitute any contravention of any law or regulation in force for the time being to which such person or action may be governed.
16. Company shall not be held responsible for any interactions/ passing of information(s) etc. between any User via e-mail, chat or any other medium with another User and Company has no obligation to monitor any such disputes arising between the Users and Company shall not be party to such dispute/litigation etc.
17. Company reserves the absolute right to modify or amend or delete, in any manner as it deems fit, any content of any matrimonial listing placed on the Platform in order to ensure compliance with the rules of such placement (which may include, without limitation, the efforts and initiatives by Company to maximize response to matrimonial listings), prima facie accuracy and the prevailing laws in force for the time being, especially those relating to prohibition of any indecent, unlawful or obscene content. Company reserves the absolute right to delete any profile if it finds that the same person has created multiple profiles on the Platform. Even if different profiles have been created with the same contact details, Company will reserve the absolute right to delete all such profiles. If any member refuses to give consent to a physical address verification that Company has requested then Company will have the absolute right to either put a "Not Verified" stamp on the profile or to delete the profile.
18. Websites to which links are given on the Platform and the contents thereof are the sole responsibility of the promoters of such websites and Company does not, in any manner whatsoever, recommend, authenticate, endorse, verify or certify these websites or any contents or links there. Company does not take any responsibility for the privacy practice adopted by such other websites and therefore Company recommends Users to read the privacy statement of each and every website that they visits. Company also does not take any responsibility or endorse the authenticity of the other online services displayed on the Platform which may offer various services like a lucky draw, win a free trip, win free tickets, astrology, palmistry, numerology etc. User of the Platform shall at its sole risk and responsibility click and surf on to such other website(s) / links which is/are being displayed on the Platform. Users shall always bear in mind that at a single stroke/click of the mouse on such links/website, it gets connected through the Transmission Control Protocol (TCP) / Internet Protocol (IP) network of the said Users and not through the IP of the Platform. Company also does not suggest/encourage Users to furnish personal information and specially the Profile ID / User Name of the User on the Platform to such or any other website(s).
19. Company reserves the right to tie up with partners in future to come up with various other online services. However, Company shall never share the information / data collected from Users with such other partners without taking prior consent / permission from such Users. Company in such circumstances suggests that Users peruse the privacy policy of such partners before giving their consent or before furnishing personal identifiable information with such other website(s). Company is not privy to the privacy practice adopted by its partners and does not take the responsibility in respect of the privacy policy adopted / to be adopted by such partners. Company also reserves the right to use / share the information / data collected from Users with its partners if a User has already made public the information / data to Users of the Platform.
20. Company hereby specifically disclaims any liabilities or warranties or guarantees, express, specific or implied, which may be attributable, in any manner whatsoever, to the existence, promotion, canvassing, contents, links, information or discontinuance of the Platform. No claims for damages, restitution, loss-of-profits, or any other pecuniary, civil or criminal claimants, which may be said to arise out, or on account, of any matter contained or related to the Platform, shall lie or be deemed to be sustainable against the Company.
21. Company assumes no responsibility for any error, omission, interruption, deletion, defect, delay in operation or transmission, communications line failure, theft or destruction or unauthorized access to, or alteration of User communications. Company is not responsible for any problems or technical malfunction of any telephone network or lines, computer online systems, servers or providers, computer equipment, software, failure of e-mail or players on account of technical problems or traffic congestion on the internet or at any website or combination thereof, including injury or damage to Users or to any other person's computer related to or resulting from participating or downloading materials /information from the Platform.
22. Users who visit the Platform are classified by the Company as Users with incomplete or complete profiles. Both these types could further be free members or paid members. Company reserves the absolute right to modify, amend, change, curtail or expand any privileges, rights, benefits, liabilities or responsibilities of all types of paid Users or free Users as it deems fit and these will be instantly applicable to all past, present and future Users. Company allows free Users certain benefits /privileges like initiating free contact via "Express Interest" functionality, like viewing contact details of paid Users under certain conditions etc. The quantum of these benefits and even the benefits in totality will be at the sole discretion of the Company. Company will determine at its own discretion how many benefits it offers to every free User. Company  will simultaneously offer different levels of benefits to different free Users Benefit restrictions to free Users will be done via multiple means including restricting access, spam filters, quotas etc.
23. Payments for the services offered on the Platform shall be on a 100% advance basis. The payment for service once subscribed to by the User is not refundable and any amount paid shall stand appropriated. Refund if any will be at the sole discretion of the Company and it offers no guarantees whatsoever for the accuracy or timeliness of the refunds reaching the User’s card/bank accounts.  Company gives no guarantees of server uptime or applications working properly. All is on a best effort basis and Company’s liability for losses, damages and claims hereunder is limited to refund of amount only. Company undertakes no liability for free services. Company reserves its right to amend / alter or change all or any disclaimers or these Terms at any time without any prior notice.  All terms / disclaimers whether specifically mentioned or not shall be deemed to be included if any reference is made to them. The continued usage of the Platform by a User shall constitute deemed acceptance by the User of the amended Terms.
  
24. The User is solely and exclusively responsible for maintaining confidentiality of the User password and User identification and all activities and transmission performed by the User through his/her user identification and shall be solely responsible for carrying out any online or off-line transaction involving credit cards / debit cards or such other forms of instruments or documents for making such transactions and Company assumes no responsibility or liability for their improper use of information relating to such usage of credit cards / debit cards used by the subscriber online / offline. Company uses reasonable care as is necessary to ensure that all or any data / information does not fall in the wrong hands. The weak link in credit card transactions is securely storing the data once received; therefore Company does not store or keep credit card/debit card/bank account. For the purposes of ensuring the maximum security for the financial information of a user (such as credit card/debit card/internet banking data) all such online payment transactions are carried out directly on the secured platforms of payment gateways and not on the Platform.
25. Company does not warrant that the Platform will be uninterrupted or error-free. Company provides the service on an "as is" basis. However, Company will take all reasonable steps to provide its users with error free, uninterrupted user experience. There may be delays, omissions, and interruptions in the availability of the Platform. Users acknowledge that use of the Platform is solely at their cost and risk. Company is not responsible for suspension of the services on the Platform, irrespective of the reason for such interruption / suspension. Company may discontinue or change the services on the Platform or its availability at any time, and the User is also free to stop availing the services on the Platform at any time.
26. The Company uses third party payment gateways on the Platform and failures in these gateways would be communicated to the users as it is. Extra currency/conversion charges/deductions/error issues from payment gateway shall not be the responsibility of the Company.
27. Company has complete rights in the Platform and the services provided thereunder. The Platform contains to the extent protected by applicable laws, copyrighted material, trademarks, and other proprietary information of its owners and its licensors. Except for that information which is in the public domain or for any other information/display for which permission have not been obtained from Company, Company reserves the right to proceed/initiate appropriate steps under the prevailing law against infringement of the said proprietary rights for illegal copying, modifying, publishing, transmitting, distributing, performing, displaying, or selling of any such proprietary information.
28. Company reserves the right to verify the authenticity of Content posted on the site. Company if circumstances warrant may call for / ask any of its Users to provide documentary or other form of evidence supporting the information / User Data posted on the Platform and the User, without any protest shall produce such documentary / other evidence in support of such information and if the User fails to produce such information within a reasonable or stipulated time frame, Company may, in its sole discretion, terminate the profile/access to the Platform and forfeit the advance without a refund and take appropriate steps under the provisions of law. Company also reserves the right to investigate and take appropriate legal action without limitation at its sole discretion against any User who violates / misuses the online services and terminating the profile/access to the Platform of such violators without prior intimation who utilise the Platform in any manner which brings into disrepute or impairs the interests and functioning of Platform or the Company.
29. Company also reserves the right to investigate and take appropriate legal action without limitation at its sole discretion against any User who violates / misuses the online services and terminating the profile/access to the Platform of such violators without prior intimation who utilise the Platform in any manner which brings into disrepute or impairs the interests and functioning of Platform or the Company.
30. Company does not take the responsibility of any information posted by its Users on the Platform, any copyrighted material, trademarks, or other proprietary information without obtaining the prior written consent of the owner of such proprietary rights and in case Company receives/discovers any such infringement, the said User may be called for / asked to furnish / provide evidence / relevant information in support of such display like an electronic or physical signature of the person authorized to act on behalf of the owner of the copyright interest or a description of the copyrighted work that may have been infringed or information or a written statement that the User under bona-fide faith belief that the disputed information does not lead to any authorized use or infringement of copyright etc, under the law or a statement that the User is liable to penalty of perjury in case any of the information/statement furnished is proved otherwise or a declaration that the information displayed/posted is accurate and the User is itself the copyright owner or authorized to act on the copyright owner's behalf.
31. Company has no obligation to monitor the activities of its Users. However, Company has the right to monitor the Platform electronically from time to time and to disclose any information as necessary to satisfy any law, regulation or other governmental request, to operate the Platform properly, or to protect itself or its Users. Company also reserves the right to refuse to post or to remove any information or materials, in whole or in part, that, in its sole discretion, are unacceptable, undesirable, or violative of provision of law.
32. The usage of this Platform and any disputes/issues arising out of it shall be subject to the applicable laws in force to the exclusive jurisdiction of courts located in Bhopal MP.
33. All members of Platform are restricted to the following number of contacts they can make via the "Express Interest" option on the Platform.
 
34. In case Company receives any incriminating evidence/complaint against any User from other Users of the Platform or if Company, through data available to it from its servers, suspects misbehavior on any User’s part, it reserves the right to impose restrictions on the User’s account which include but may not be confined to preventing the User under question from making multiple contacts and restricting the user to only contact members whose desired partner profile the User satisfies.
35. All services which are defined by time period indicated in months shall imply 1 month to be equal to 30 days and for any longer durations service the total duration in days will be the number of months multiplied by 30.
36. Company guidelines prohibit members to give their name and/or contact details in any form - Email, Phone nos., Messenger Ids, Postal address etc in any fields other than the specific ones where the same information is asked. If any member who puts the above information in any field other than the one meant for that purpose then the Company screening team will remove the same.
37. Users of the Platform are consenting for receiving
a) Membership Emails: Emails conveying the benefits of paid membership to Users. These are sent to the Email address mentioned by the Users in their profile.
b) Important Notifications from the Platform – Messages/notifications are sent to Users to inform them of various alerts related to usage of the Platform. . These will be communicated to the Users by Email/app notifications etc. or on their Landline/Mobile from a non-140 number via SMS/MMS/VMS/USSD/IVR/Calls etc.
c) Membership SMSes/Calls: SMSes or phone calls shall be sent conveying the benefits of paid membership to Users. Users will receive these calls or SMS on any of the phone numbers mentioned by Users on their profile, if they have subscribed to calls/ SMS in their alert manager settings.
38. Promotional Mails - . Promotional emails are sent to members on their Email ids, if they have subscribed to promotional emails in their alert manager settings.
39. If a member does not wish to receive communication from the Company then he needs to go to the "Settings" section in his profile and choose/disable for the modes (Emails / SMS / Calls / USSD / Messenger messages / IVR) and types of communication which User either wants to or does not want to receive. Types of communication are the specific messages based on profile attribute or Platform interactions between members. Platform may also provide for different message types and modes, other alternative ways to unsubscribe".
40. Users who sign up for Rajput Lagn Exclusive services allow the Company to find suitable candidate/prospects on their behalf as per their instructions via Telephone, SMS, profile action on Rajput Lagn Platform, face to face interaction or any other means/modes of communication.
41. Creation of duplicate profile on Rajput Lagn is prohibited. In case the user has forgotten his password he can use the password retrieval option. Forgetting password, User ID, reaching contact limits or any other reason for creating a 2nd profile on Rajput Lagn is not allowed. Arkadesky technology reserves the right to delete/block this profile or restrict access of this profile to use the Platform. Arkadesky technology at its own discretion can decide to delete/block/restrict access of 2nd profile or the original profile or both profiles in all cases where duplicate profiles have been found.
42. Membership Renewal: People who have subscribed to paid services Rajput Lagn  have an option to renew their services. If the renewal happens before the expiry date, then any unused "Contact Views" available with the original pack are not carried forward except when renewing to paid plan . Contact Views are the facility wherein members can see contact details of other members who have not filtered/rejected/ignored them. If a member renews his membership after the expiry of current membership, then it is treated as a fresh membership and unused "Contact Views" of the previous membership are not carried forward. These conditions hold even if the renewal of the subscription is bundled with a special "Renewal/Repurchase/Loyalty" offer. Purchase before or after renewal date is the only criteria which determines if unused "Contact Views" are carried forward or not.
43. Your "Name" will be visible to other members who are Rajput Lagn Paid subscribers either if they "View Your Contact Details" or if you have sent them an Acceptance. Information filled by a member is visible on the profile page. This page is indexed by Google/Ask/Bing/Yahoo and other search engines. If a search engine user types a query then your profile page may be visible in Google/Bing/Yahoo etc. search results. All details which you have put will be visible unless the same has been explicitly hidden by you using appropriate Platform profile privacy settings.
44. Use of certain features on the Platform is governed by rules. For example if your phone number is not verified then you cannot contact other members via  “send interest" or even if the same is happening then that privilege can be blocked by Company at any time without giving any notice. Similarly If your phone number is not verified then even as a person who has availed a "Paid Service" you will still not be able to view phone/email/contact details of other members via any option on the Platform. For verifying your phone number, there are verification prompts across the Platform which guide you on how to verify your phone. If the same is not clear then it is the member's responsibility to call customer care of Platform from the number which he/she wishes to verify.
45. Any paid membership &Trial Pack, etc. are non-transferable. Any membership which is purchased is being purchased for that individual and cannot be used for any other profile in his/her family/friends/acquaintances etc. If a profile is deleted for whatsoever reason then that persons membership lapses.
46. At times when a member tries to access the phone/email of another member, he can get a message which asks him to "View Phone/Email tomorrow - Contact limits reached of recipient" or any message which means the same. In these cases the member just needs to visit the same profile again the next days and use his quota of "View Contacts".
47. 'Contact Details' may consist of one or more of the following details - a. Mobile number(s), b. Landline number and c. Email address. Having a paid subscription unlocks access to 'Contact Details' subject to the following conditions: i. Access to Contact Details may be restricted based on privacy settings with respect to phone number(s) or contact filters opted by the other person or if the other person has blocked, declined or cancelled interest, ii. A fair usage limit of at most 25 contact views per month of subscription duration applies for viewing contact details
 
48. Paid Membership is co-extensive with the profile, membership expires as soon as the profile is deleted and cannot be reactivated.
49. 'Featured Profile' subscribers will be considered to be shown at the top of search results only if they regularly login to their account. If 'Featured Profile' subscribers don't access the Platform for more than 15 days, they will be removed from the pool of users considered for being shown at the top of Search Page.
50. Any profile deleted by the profile user cannot be retrieved under any circumstances.
51. Coupons generated for referrals on Rajput Lagn have an expiry date of one year from the date of generation. Coupons will only be awarded to the referrer and the referee if the referee registers from the link sent by Rajput Lagn (on Email or through share options). However, coupons are not valid for USD Payments, coupons are not valid on Plan upgrades, coupon code discounts cannot be combined with any other offer on the Platform and coupons cannot be availed on two (2) month and four (4) month plans.
54. Unless otherwise specified and notwithstanding anything contained in any other agreement or arrangement, by whatever name called, the performance obligation of Company (service provider) is to provide access of its on-line portal to the customer for the duration of the subscription period & reference to any usage, by whatever name called or any other performance obligation, if any, is to provide the upper limit for consumption, which by itself, does not create any additional performance obligation upon Company.
55. We do housekeeping of profiles which are not logged in for a period of 12 months. We remove all the data associated with the profile during housekeeping.
56.Rajput lagn is not held liable for any profile frauds , users are advised to kindly verify the profiles personally for assurance. If any profile found suspicious you can report by writing mail, we ll scrutinize and remove the profile.
57. The pricing and the contact views allotted will be on a prorata basis as computed by Rajput Lagn. The plan upgrades will be valid till the expiry of the original plan bought.
Restriction / Prohibitions
The following actions will inter alia constitute a misuse of the Platform and are strictly prohibited:
(i) Copying, extracting, downloading, sharing, modifying, selling, storing, distributing, making derivative works from or otherwise exploiting any content, data, information, including profiles, curriculum vitae, photographs and/or graphics, available on the Platform and/or any services or products of the Company, in any manner or for any purpose which is not, consistent with the Purpose and/or in accordance with the Terms of Use.
Users are expressly prohibited from using or exploiting the Platform and/or any content or data provided therein for:
(a) any commercial purposes such as creating alternate databases, extending access to the Platform to third parties without prior written consent of the Company; and/or
(b) undertaking any business activity which is in competition with the business of the Company; and/or
(c) for seeking fees in any name whatsoever; and/or
(d) approaching candidates/jobseekers for any purposes other than for specific existing vacancies; and/or
(e) Sharing access with persons who are not contracted with the Company.
(f) Reselling the products/services offered by the Company.
(ii) (Using or attempting to use any automated program, software or system or any similar or equivalent process (including spiders, robots, crawlers etc.) to access, navigate, search, copy, monitor, download, scrape, crawl or otherwise extract in any manner, any data or content including but not limited to adding or downloading profiles, contact details, or send or redirect messages from the Platform;
(iii) Gaining or attempting to gain unauthorized access (inter alia by hacking, password “mining” or any other means) to:
(a) any portion or feature of the Platform or any of the services or products offered on or through the Platform which are not intended for you;
(b) any server, website, program or computer systems of the Company or any other third parties and/or Users;
(iv) Modifying the services provided through the Platform or their appearance using any technology or overlay any additional offering on top of such services or simulate the Platform’s services or its functions in any manner whatsoever without explicit consent obtained in writing by approaching us at hello@Rajput Lagn.com.
(v) Accessing the Platform through interfaces other than those expressly provided by Company;
(vi) Attempting to breach or breaching any security or authentication measures set up by the Company in relation to the Platform and/or attempting to probe, scan or test the vulnerability of the Company’s system or network;
(vii) Scraping, downloading (including bulk- downloading), replicating or otherwise extracting any information or data from the Platform (by any process, whether automatic or manual) to offer any products or services which are similar to or may in any manner compete with the products or services of the Company;
(viii) Reverse engineering, decompiling, disassembling, deciphering or otherwise attempting to do any of the aforesaid or deriving the source code for the Site or Application or any related technology or any part thereof;
(ix) Circumventing or attempting to circumvent any technological protections used or employed by the Company or by any third party in order to protect the content on the Platform and/or to exclude robots, spiders etc. from crawling and /or scraping content from the Platform.
(x) Bypassing or Circumventing or trying to circumvent any service limits including but not limited to Search limits, Captcha limits and occurrences on different triggers
(xi) Interfering with or disrupting or attempting to interfere with or disrupt (including by using any device, software or routine), the use of the Platform or any computer networks connected to the Platform, by any other User;
(xii) Developing, using or attempting to use any automated program, scripts, robots, third party software or system or any similar or equivalent process (including spiders, robots, crawlers, browser plug-ins/extensions/add-ons, iframes on third party sites, mirroring, HTML parsers etc.) to access, navigate, search, copy, monitor, download, scrape, crawl or otherwise extract or modify  in any manner, any data or content from the Platform without explicit consent obtained in writing by approaching us at hello@Rajput Lagn.com;
(xiii) Impersonating any other person or entity, or making any misrepresentation as to your employment by or affiliation with any person or entity;
(xiv) Forging headers or in any manner manipulating identifiers in order to disguise the origin of any user information;
(xv) Stalking, threatening, or in any manner harassing any other User;
(xvi) Imposing an unreasonable or disproportionately large load on the Platform infrastructure;
(xvii) Engaging in “framing,” “mirroring,” or otherwise simulating the appearance or function of the Platform (or any part thereof) and providing deeplinks into this Platform (or any part thereof) without prior permission of Company;
(xviii) Spamming the Platform/Company or any other Users including by uploading, posting, emailing, SMS, transmitting or otherwise making available either directly or indirectly, any unsolicited bulk e-mail or unsolicited commercial e-mail.
(xix) Using the Platform or the contact details of Users for transmitting marketing and promotional mailers/ Offensive messages/ messages or communications using any media that are unrelated to recruitment or sending unsolicited commercial communications with misleading subject lines in order to intentionally obfuscate the original message.
(xx) Hosting, modifying, uploading, posting, transmitting, publishing, or distributing any material or information that:
a. Violates any applicable local, provincial, state, national or international law, statute, ordinance, rule or regulation for the time being in force;
b. Belongs to another person and to which you have no right;
c. Infringes, breaches or otherwise contravenes the rights of the Company or any third party, including any copyright, trademark, patent, rights of privacy or publicity or any other proprietary rights;
d. Contains computer viruses, or other computer code, files or programs designed to disrupt, destroy or interfere with or limit the functioning of the Platform, or any other computer system or resource;
e. Is grossly harmful, harassing, invasive of another's privacy, hateful, disparaging, relating to or encouraging money laundering or gambling in any manner, any content which is or may potentially be perceived as being harmful, threatening, abusive, harassing, defamatory, libelous, blasphemous, vulgar, pornographic, paedophilic, obscene, or racially, ethnically, or otherwise unlawful in any manner whatsoever;
f. Which constitutes or encourages conduct that would constitute a criminal offence, give rise to other liability, or otherwise violate applicable law;
g. That deceives or misleads the addressee about the origin of such messages or communicates any information which is grossly offensive or menacing in nature;
h. That harms minors in any way;
i. That threatens the unity, integrity, defense, security or sovereignty of India, friendly relations with foreign states, or public order or causes incitement to the commission of any cognisable offence or prevents investigation of any offence or is insulting to any other nation.


                        </Text>
                    </View>
                </ScrollView>
            </View>
        )
    }
}